import React from 'react';
import { Sparkles, User, Settings } from 'lucide-react';
import { AuthSessionState } from '../../types/pnbox';

interface PnboxNavbarProps { authSession: AuthSessionState; onOpenBackendSettings: () => void; onOpenAiCopilot: () => void; onNavigateHome: () => void; currentView: 'plans' | 'tools_matrix' | 'tool_detail'; userName?: string; }

export const PnboxNavbar: React.FC<PnboxNavbarProps> = ({ authSession, onOpenBackendSettings, onOpenAiCopilot, onNavigateHome, userName = 'Usuário' }) => {
  const isAuthenticated = authSession.status === 'authenticated' && !authSession.isExpired && authSession.modoExecucao === 'LIVE';
  return <header className="w-full bg-[#18163f] border-b border-[#2d2a63] text-white select-none">
    <div className="w-full bg-[#131135] px-4 sm:px-8 py-1.5 flex items-center justify-between text-[11px] text-slate-300 border-b border-[#242152]"><span>Acessibilidade</span><a href="https://sebrae.com.br" target="_blank" rel="noopener noreferrer" className="text-slate-400 hover:text-white">Ir para o Portal Sebrae →</a></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-8 py-3 flex items-center justify-between gap-4">
      <div onClick={onNavigateHome} className="flex items-center gap-3 cursor-pointer" title="Ir para Meus Planos PNBOX"><div className="w-8 h-8 grid grid-cols-2 gap-0.5 p-0.5 bg-[#252258] rounded-md"><div className="bg-[#ff2d78] rounded-[2px]"/><div className="bg-[#1877f2] rounded-[2px]"/><div className="bg-[#4f46e5] rounded-[2px]"/><div className="bg-[#00c6ff] rounded-[2px]"/></div><div><div className="flex items-center gap-1.5"><span className="text-xl font-black tracking-tight text-white lowercase">pnbox</span><span className="text-[10px] uppercase font-bold tracking-wider px-1.5 py-0.2 bg-white/10 text-pink-300 border border-pink-500/30 rounded-full font-mono">+ IA Copilot</span></div><span className="text-[9px] text-indigo-300/80">Sebrae • Plano de Negócios Inteligente</span></div></div>
      <div className="hidden md:flex items-center gap-3"><button onClick={onOpenAiCopilot} className="flex items-center gap-2 px-3 py-1.5 bg-gradient-to-r from-indigo-600 to-pink-600 text-white rounded-full text-xs font-semibold"><Sparkles className="w-3.5 h-3.5"/>Copiloto IA Ativo</button><button onClick={onOpenBackendSettings} className={`flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-medium border ${isAuthenticated ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' : 'bg-amber-500/10 border-amber-500/30 text-amber-300'}`}><span className={`h-2 w-2 rounded-full ${isAuthenticated ? 'bg-emerald-400' : 'bg-amber-400'}`}/><span>{isAuthenticated ? 'Sebrae LIVE' : 'Sebrae desconectado'}</span></button></div>
      <div className="flex items-center gap-2 sm:gap-3"><button onClick={onOpenBackendSettings} className="p-2 rounded-full hover:bg-white/10 text-slate-300" title="Configurações de conexão"><Settings className="w-4 h-4"/></button><div onClick={onOpenBackendSettings} className="flex items-center gap-2 pl-2 border-l border-white/10 cursor-pointer" title={`Conectado como ${userName}`}><div className="w-8 h-8 rounded-full bg-gradient-to-tr from-indigo-500 to-blue-500 flex items-center justify-center"><User className="w-4 h-4"/></div><div className="hidden xl:flex flex-col text-left"><span className="text-xs font-semibold">{userName}</span><span className="text-[10px] text-indigo-300/70">{isAuthenticated ? 'Conta Oficial Sebrae' : 'Sem conexão PNBOX'}</span></div></div></div>
    </div>
  </header>;
};
